/**
 * Socket Event Names dùng để giao tiếp giữa Client và Server
 * (Giải quyết vấn đề N2)
 */
export const SOCKET_EVENTS = {
  // Client to Server
  GET_ROOMS: 'GET_ROOMS',
  GET_ROOM: 'GET_ROOM',
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  START_GAME: 'START_GAME',
  KICK_PLAYER: 'KICK_PLAYER',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  SEND_CHAT: 'SEND_CHAT',
  CAST_VOTE: 'CAST_VOTE',
  NIGHT_ACTION: 'NIGHT_ACTION',
  WOLF_DRAFT_TARGET: 'WOLF_DRAFT_TARGET',
  WITCH_ACTION: 'WITCH_ACTION',
  CUPID_ACTION: 'CUPID_ACTION',
  HUNTER_SHOOT: 'HUNTER_SHOOT',
  HUNTER_SKIP: 'HUNTER_SKIP',
  RECONNECT_ROOM: 'RECONNECT_ROOM',
  RESET_ROOM: 'RESET_ROOM',
  DISCONNECT: 'disconnect',

  // Server to Client
  ROOM_LIST: 'ROOM_LIST',
  ROOM_UPDATED: 'ROOM_UPDATED',
  GAME_RESET: 'GAME_RESET',
  GAME_STATE_UPDATE: 'GAME_STATE_UPDATE',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  VOTE_UPDATED: 'VOTE_UPDATED',
  VOTING_RESULT: 'VOTING_RESULT',
  NIGHT_ACTION_PROMPT: 'NIGHT_ACTION_PROMPT',
  NIGHT_STATUS_UPDATE: 'NIGHT_STATUS_UPDATE',
  FIRST_NIGHT_LOVERS_REVEAL: 'FIRST_NIGHT_LOVERS_REVEAL',
  FIRST_NIGHT_WOLF_REVEAL: 'FIRST_NIGHT_WOLF_REVEAL',
  WOLF_VOTE_UPDATED: 'WOLF_VOTE_UPDATED',
  WOLF_TARGET_SELECTED: 'WOLF_TARGET_SELECTED',
  HUNTER_RETALIATION_PROMPT: 'HUNTER_RETALIATION_PROMPT',
  HUNTER_SHOT_RESULT: 'HUNTER_SHOT_RESULT',
  RECONNECT_SUCCESS: 'RECONNECT_SUCCESS',
  SEER_RESULT: 'SEER_RESULT',
  KICKED: 'KICKED'
} as const;
